164.41.86.12:
  80:
    hostname: apache
    port: 80

  443:
    hostname: apache
    port: 443

  21:
    hostname: services
    port: 22


164.41.86.15:
  80:
    hostname: letsencrypt
    port: 80

  443:
    hostname: letsencrypt
    port: 443

  21:
    hostname: letsencrypt
    port: 22
