default['gpg']['key_type']      = 'RSA'
default['gpg']['key_lenght']    = '2048'
default['gpg']['batch_conf']    = '/tmp/gpg_batch_conf'
default['gpg']['expire_date']   = '0'

default['gpg']['name_real']     = 'Lappis Debian Repository'
default['gpg']['name_comment']  = 'generated by Chef'
default['gpg']['name_email']    = 'webmaster.fga@gmail.com'

default['gpg']['user']    = 'root'
# Should be used to not store the master key on the server
# default['gpg']['subkeys'] = ['C0544B14']
