#! /bin/sh -
# /etc/init.d/codeschool
#

### BEGIN INIT INFO
# Provides:          codeschool
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

case "$1" in
  start)
    echo "Starting Codeschool"
    sh /app/codeschool/start-site.sh
    ;;
  stop)
    echo "Stopping Codeschool"
    PID="$(docker ps | awk '{print $1}' | sed -n 2p)"
    docker stop "${PID}"
    ;;
  *)
    echo "Usage: /etc/init.d/ {start|stop}"
    exit 1
    ;;
esac

exit 0
