#!/bin/bash

BACKUP_DIR=/var/local/2017.1-PlataformaJogosUnB/backup
BACKEND_DIR=/var/local/2017.1-PlataformaJogosUnB/backend
BACKUP_CMD="python3 manage.py generate_backup"

LOG_FILE=/var/log/unbgames_backup.log
LOG_FORMAT=[%b_%a_%Y-%m-%d-%R][unbgames-backup]

echo "Data do backup: " $(date +%Y/%m/%d-%R)

# Running unbgames backup task
cd $BACKEND_DIR
echo $(date +$LOG_FORMAT) \
  $($BACKUP_CMD) >> $LOG_FILE
